Repository exercism/elm, pull requests merged in 2021-05, with the labels that each got.

#363 🤖 Add stub files to all exercises
  exercises/practice/pascals-triangle/.meta/src/PascalsTriangle.example.elm
  exercises/practice/pascals-triangle/src/PascalsTriangle.elm
  exercises/practice/pascals-triangle/tests/Tests.elm
Labels: v3-migration 🤖

#362 🤖 Simplify tests.toml files
  exercises/practice/acronym/.meta/tests.toml
  exercises/practice/all-your-base/.meta/tests.toml
  exercises/practice/allergies/.meta/tests.toml
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/armstrong-numbers/.meta/tests.toml
  exercises/practice/atbash-cipher/.meta/tests.toml
  exercises/practice/binary-search/.meta/tests.toml
  exercises/practice/bob/.meta/tests.toml
  exercises/practice/collatz-conjecture/.meta/tests.toml
  exercises/practice/difference-of-squares/.meta/tests.toml
  exercises/practice/etl/.meta/tests.toml
  exercises/practice/gigasecond/.meta/tests.toml
  exercises/practice/grade-school/.meta/tests.toml
  exercises/practice/grains/.meta/tests.toml
  exercises/practice/hamming/.meta/tests.toml
  exercises/practice/hello-world/.meta/tests.toml
  exercises/practice/isogram/.meta/tests.toml
  exercises/practice/largest-series-product/.meta/tests.toml
  exercises/practice/leap/.meta/tests.toml
  exercises/practice/list-ops/.meta/tests.toml
  exercises/practice/luhn/.meta/tests.toml
  exercises/practice/matching-brackets/.meta/tests.toml
  exercises/practice/nucleotide-count/.meta/tests.toml
  exercises/practice/pangram/.meta/tests.toml
  exercises/practice/pascals-triangle/.meta/tests.toml
  exercises/practice/phone-number/.meta/tests.toml
  exercises/practice/pythagorean-triplet/.meta/tests.toml
  exercises/practice/raindrops/.meta/tests.toml
  exercises/practice/rna-transcription/.meta/tests.toml
  exercises/practice/robot-simulator/.meta/tests.toml
  exercises/practice/roman-numerals/.meta/tests.toml
  exercises/practice/run-length-encoding/.meta/tests.toml
  exercises/practice/say/.meta/tests.toml
  exercises/practice/scrabble-score/.meta/tests.toml
  exercises/practice/series/.meta/tests.toml
  exercises/practice/space-age/.meta/tests.toml
  exercises/practice/sublist/.meta/tests.toml
  exercises/practice/sum-of-multiples/.meta/tests.toml
  exercises/practice/transpose/.meta/tests.toml
  exercises/practice/triangle/.meta/tests.toml
  exercises/practice/twelve-days/.meta/tests.toml
  exercises/practice/two-fer/.meta/tests.toml
  exercises/practice/word-count/.meta/tests.toml
  exercises/practice/wordy/.meta/tests.toml
Labels: v3-migration 🤖

#364 🤖 Add fetch configlet script(s) to CODEOWNERS file
  .github/CODEOWNERS
Labels: v3-migration 🤖

#367 🤖 Add average test runner run time to `config.json`
  config.json
Labels: v3-migration 🤖

#370 Fix the naming of files to make configlet happy
  exercises/practice/pascals-triangle/.meta/config.json
  exercises/practice/rna-transcription/.meta/config.json
  exercises/practice/rna-transcription/.meta/src/RnaTranscription.example.elm
  exercises/practice/rna-transcription/src/RnaTranscription.elm
  exercises/practice/rna-transcription/tests/Tests.elm
Labels: reputation/contributed_code/minor

#371 🤖 Remove `online_editor.ace_editor_language` key
  config.json
Labels: v3-migration 🤖

#365 Add list concept and associated exercise
  concepts/lists/.meta/config.json
  concepts/lists/about.md
  concepts/lists/introduction.md
  concepts/lists/links.json
  config.json
  exercises/concept/tracks-on-tracks-on-tracks/.docs/hints.md
  exercises/concept/tracks-on-tracks-on-tracks/.docs/instructions.md
  exercises/concept/tracks-on-tracks-on-tracks/.docs/introduction.md
  exercises/concept/tracks-on-tracks-on-tracks/.meta/Exemplar.elm
  exercises/concept/tracks-on-tracks-on-tracks/.meta/config.json
  exercises/concept/tracks-on-tracks-on-tracks/.meta/design.md
  exercises/concept/tracks-on-tracks-on-tracks/elm.json
  exercises/concept/tracks-on-tracks-on-tracks/src/TracksOnTracksOnTracks.elm
  exercises/concept/tracks-on-tracks-on-tracks/tests/Tests.elm
Labels: reputation/contributed_code/major
