Repository exercism/elm, pull requests merged in 2022-03, with the labels that each got.

#475 Rewrite `robot-simulator` tests that the Elm test runner can't parse
  exercises/practice/robot-simulator/tests/Tests.elm
Labels: x:action/fix, x:module/practice-exercise, x:size/small

#473 Format config files and enable `configlet fmt` on CI
  .github/org-wide-files-config.toml
  exercises/concept/annalyns-infiltration/.meta/config.json
  exercises/concept/bandwagoner/.meta/config.json
  exercises/concept/bettys-bike-shop/.meta/config.json
  exercises/concept/go/.meta/config.json
  exercises/concept/lucians-luscious-lasagna/.meta/config.json
  exercises/concept/luigis-luscious-lasagna/.meta/config.json
  exercises/concept/role-playing-game/.meta/config.json
  exercises/concept/ticket-please/.meta/config.json
  exercises/concept/tisbury-treasure-hunt/.meta/config.json
  exercises/concept/tracks-on-tracks-on-tracks/.meta/config.json
  exercises/concept/valentines-day/.meta/config.json
  exercises/practice/accumulate/.meta/config.json
  exercises/practice/acronym/.meta/config.json
  exercises/practice/all-your-base/.meta/config.json
  exercises/practice/allergies/.meta/config.json
  exercises/practice/anagram/.meta/config.json
  exercises/practice/armstrong-numbers/.meta/config.json
  exercises/practice/atbash-cipher/.meta/config.json
  exercises/practice/binary-search/.meta/config.json
  exercises/practice/bob/.meta/config.json
  exercises/practice/bowling/.meta/config.json
  exercises/practice/collatz-conjecture/.meta/config.json
  exercises/practice/difference-of-squares/.meta/config.json
  exercises/practice/etl/.meta/config.json
  exercises/practice/gigasecond/.meta/config.json
  exercises/practice/grade-school/.meta/config.json
  exercises/practice/grains/.meta/config.json
  exercises/practice/hamming/.meta/config.json
  exercises/practice/hello-world/.meta/config.json
  exercises/practice/isogram/.meta/config.json
  exercises/practice/largest-series-product/.meta/config.json
  exercises/practice/leap/.meta/config.json
  exercises/practice/list-ops/.meta/config.json
  exercises/practice/luhn/.meta/config.json
  exercises/practice/matching-brackets/.meta/config.json
  exercises/practice/nucleotide-count/.meta/config.json
  exercises/practice/pangram/.meta/config.json
  exercises/practice/pascals-triangle/.meta/config.json
  exercises/practice/phone-number/.meta/config.json
  exercises/practice/pythagorean-triplet/.meta/config.json
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/rna-transcription/.meta/config.json
  exercises/practice/robot-simulator/.meta/config.json
  exercises/practice/roman-numerals/.meta/config.json
  exercises/practice/run-length-encoding/.meta/config.json
  exercises/practice/say/.meta/config.json
  exercises/practice/scrabble-score/.meta/config.json
  exercises/practice/series/.meta/config.json
  exercises/practice/space-age/.meta/config.json
  exercises/practice/strain/.meta/config.json
  exercises/practice/sublist/.meta/config.json
  exercises/practice/sum-of-multiples/.meta/config.json
  exercises/practice/transpose/.meta/config.json
  exercises/practice/triangle/.meta/config.json
  exercises/practice/twelve-days/.meta/config.json
  exercises/practice/two-fer/.meta/config.json
  exercises/practice/word-count/.meta/config.json
  exercises/practice/wordy/.meta/config.json
Labels: x:type/ci, x:size/small

#468 Correct typo
  concepts/tuples/about.md
  concepts/tuples/introduction.md
  exercises/concept/tisbury-treasure-hunt/.docs/introduction.md
Labels: x:size/tiny

#476 Add task ID tags to concept exercise tests
  .github/workflows/build.yml
  bin/build.sh
  elm-tooling.json
  exercises/concept/annalyns-infiltration/tests/Tests.elm
  exercises/concept/bandwagoner/tests/Tests.elm
  exercises/concept/bettys-bike-shop/tests/Tests.elm
  exercises/concept/go/tests/Tests.elm
  exercises/concept/lucians-luscious-lasagna/tests/Tests.elm
  exercises/concept/luigis-luscious-lasagna/tests/Tests.elm
  exercises/concept/role-playing-game/tests/Tests.elm
  exercises/concept/ticket-please/tests/Tests.elm
  exercises/concept/tisbury-treasure-hunt/tests/Tests.elm
  exercises/concept/tracks-on-tracks-on-tracks/tests/Tests.elm
  exercises/concept/valentines-day/tests/Tests.elm
Labels: x:module/concept-exercise, x:size/large

#478 Apply `elm-review` suggestions to Example/Exemplar solutions
  exercises/concept/tracks-on-tracks-on-tracks/.meta/Exemplar.elm
  exercises/practice/acronym/.meta/src/Acronym.example.elm
  exercises/practice/allergies/.meta/src/Allergies.example.elm
  exercises/practice/atbash-cipher/.meta/src/AtbashCipher.example.elm
  exercises/practice/binary-search/tests/Tests.elm
  exercises/practice/gigasecond/tests/Tests.elm
  exercises/practice/grade-school/.meta/src/GradeSchool.example.elm
  exercises/practice/grains/tests/Tests.elm
  exercises/practice/list-ops/tests/Tests.elm
  exercises/practice/luhn/.meta/src/Luhn.example.elm
  exercises/practice/matching-brackets/.meta/src/MatchingBrackets.example.elm
  exercises/practice/matching-brackets/tests/Tests.elm
  exercises/practice/phone-number/.meta/src/PhoneNumber.example.elm
  exercises/practice/raindrops/.meta/src/Raindrops.example.elm
  exercises/practice/rna-transcription/.meta/src/RnaTranscription.example.elm
  exercises/practice/run-length-encoding/.meta/src/RunLengthEncoding.example.elm
  exercises/practice/two-fer/tests/Tests.elm
  exercises/practice/word-count/tests/Tests.elm
Labels: x:action/improve, x:size/small
